version: '3.1'
services:
  db:
    container_name: db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: main
    ports:
      - 15432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 18080:8080